// <auto-generated />
using System;
using ASPNETITSTEP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPNETITSTEP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260827163116_UpdatedDk")]
    partial class UpdatedDk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ASPNETITSTEP.Data.Entities.UserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96dcbbba-9aee-44a2-8835-72dfe4e1a710"),
                            Dk = "FCB57CECE720632FDBB68958CF953E46",
                            Login = "Admin",
                            RoleId = new Guid("702d05c2-fcd0-4c1d-b0bb-2aeb4b98f91a"),
                            Salt = "96DCBBBA-9AEE-44A2-8835-72DFE4E1A710",
                            UserId = new Guid("190052ca-f844-498a-a05f-1d4ba2adc0e8")
                        });
                });

            modelBuilder.Entity("ASPNETITSTEP.Data.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsersData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("190052ca-f844-498a-a05f-1d4ba2adc0e8"),
                            BirthDate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "CHANGE@ME",
                            FullName = "Адміністратор системи",
                            Phone = "CHANGE_ME",
                            RegisteredAt = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ASPNETITSTEP.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeleteLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdateLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UsersRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acb35324-7b84-4e3b-9a26-00aad72a600c"),
                            CreateLevel = 10,
                            DeleteLevel = 10,
                            Description = "Кореневий адміністратор",
                            Name = "Admin",
                            ReadLevel = 10,
                            UpdateLevel = 10
                        },
                        new
                        {
                            Id = new Guid("702d05c2-fcd0-4c1d-b0bb-2aeb4b98f91a"),
                            CreateLevel = 0,
                            DeleteLevel = 0,
                            Description = "Самозаєстрований користувач",
                            Name = "User",
                            ReadLevel = 0,
                            UpdateLevel = 0
                        });
                });

            modelBuilder.Entity("ASPNETITSTEP.Data.Entities.UserAccess", b =>
                {
                    b.HasOne("ASPNETITSTEP.Data.Entities.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPNETITSTEP.Data.Entities.UserData", "UserData")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("ASPNETITSTEP.Data.Entities.UserData", b =>
                {
                    b.Navigation("Accesses");
                });
#pragma warning restore 612, 618
        }
    }
}
